# Vngo application settings
vngo:
  image:
    repository: nguyenphuc4444/vngo
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  env:
    springProfile: dev

# MySQL settings
mysql:
  enabled: false
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  auth:
    rootPassword: my_root_password
    database: vngo_db
    username: vngo_user
    password: vngo_password
  service:
    port: 3306

# Application environment variables
env:
  DB_URL: "jdbc:mysql://vngo-mysql:3306/vngo_db"
  DB_USERNAME: "vngo_user"
  DB_PASSWORD: "vngo_password"
  SPRING_PROFILES_ACTIVE: ""