# Vngo application settings
vngo:
  image:
    repository: nguyenphuc4444/vngo
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 8080

# MySQL settings
mysql:
  enabled: false
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    port: 3306
  auth:
    database: vngo_db

# Application environment variables
env:
  SPRING_PROFILES_ACTIVE: "default"