apiVersion: v1
kind: Secret
metadata:
  name: vngo-secret
type: Opaque
data:
  db-username: {{ "vngo_user" | b64enc }}
  db-password: {{ "vngo_password" | b64enc }}
  jwt-signer-key: {{ "UH2pUuhi1v0NRutqBHtf7dVuCb6kwnMOAFIfoCzMmYQ=" | b64enc }}