apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vngo
  labels:
    app: {{ .Release.Name }}-vngo
spec:
  type: {{ .Values.vngo.service.type }}
  ports:
  - port: {{ .Values.vngo.service.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-vngo